### ISSUE TITLE
Typo on preference screen

### ISSUE THREAD

**Issue by bbendick** [mitchelljfranklin/Boomi-Platform-Extension#20]
"Adjust to suite your needs." should be "Adjust to suit your needs."

**Comment by mitchelljfranklin** [comment]
Fixed by @matt-flaig and will be on next release

**Comment by mitchelljfranklin** [comment]
Imported and committed to next release under 68fd04d

**Comment by mitchelljfranklin** [comment]
Closing issue due to fix being released in 1.7.4.3
