### ISSUE TITLE
Ability to disable "toggle table line wrap"

### ISSUE THREAD

**Issue by bbendick** [mitchelljfranklin/Boomi-Platform-Extension#21]
I would like to disable the "toggle table line wrap" feature. It's not something I've used, but more importantly tends to appear and disappear randomly and quickly. It's not literally random, it's very predictable. Just in the sense that it often pops up when not expecting it.

**Comment by mitchelljfranklin** [comment]
Code update pushed in commit 189c69d, will be available in next release

**Comment by mitchelljfranklin** [comment]
Closing issue due to fix being released in 1.7.4.3
