### ISSUE TITLE
July 2023 Changes - Side Menu Change Padding between Objects

### ISSUE THREAD

**Issue by mitchelljfranklin** [mitchelljfranklin/Boomi-Platform-Extension#24]
New Design change added a fair bit of padding between the menu objects, takes up space and prevents showing more detail.

![image](https://github.com/mitchelljfranklin/Boomi-Platform-Extension/assets/56988354/90eedf71-e60a-47ab-a669-30babf5bf7b0)

**Comment by matt-flaig** [comment]
Added stylistic adjustments to boomi.css in the 1.7.4.5 branch. 👍
